apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-docker-java
  template:
    metadata:
      labels:
        app: k8s-docker-java
    spec:
      containers:
      - name: springboot-container
        image: vk0docker/k8s-docker-java # Add tag if missing
        ports:
        - containerPort: 8080
